{
    'name': 'Database License & Anti-Copy Protection Manager',
    'version': '19.0.1.0.0',
    'category': 'Tools',
    'summary': 'Software License Management with UUID Locking, Anti-Copy Protection, Session Control & Email Alerts',
    'author': 'DIGITALUB ANGOLA',
    'depends': ['base', 'web', 'auth_signup', 'mail'],
    'external_dependencies': {
        'python': ['pyjwt', 'cryptography'],
    },
    'data': [
        'data/mail_template_data.xml',
        'data/ir_cron_data.xml',
        'views/res_config_settings_views.xml',
        'views/login_templates.xml',
        'views/login_warning.xml',
        'views/license_expired_templates.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'db_license_manage/static/src/css/login.css',
        ],
        'web.assets_backend': [
            'db_license_manage/static/src/js/systray_license.js',
            'db_license_manage/static/src/xml/systray_license.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'OPL-1',
    'price': 349.0,
    'currency': 'USD',
    'images': [
        'static/description/banner.png',
        'static/description/01_login_license_status.png',
        'static/description/02_user_login_blocked.png',
        'static/description/03_license_expired_systray.png',
        'static/description/04_license_configuration.png',
        'static/description/05_active_valid_license.png',
        'static/description/06_active_license_systray.png',
        'static/description/07_login_active_license.png',
        'static/description/08_anti_copy_protection.png',
        'static/description/09_odoo19_login_protection.png',
    ],
}
